Update lisp.tex
yossigil/safot pull request #92
Opened 2020-10-23 15:10 UTC by SalehKa

2020-11-10 18:41 UTC, gur111 requested changes
Please resolve all conflicts by merging with master.
```
git checkout master
git pull
git checkout -
git merge master
```
And submit for review again

2020-11-10 18:41 UTC, gur111 commented on lisp.tex
> +  \lstinputlisting[language=kernel,style=display,backgroundcolor=\color{olive!10}]{\fileName}%
Why remove the indentation?

2020-11-10 18:41 UTC, gur111 commented on lisp.tex
> +  \read\tempFile to\fileline % Read one line and store it into \fileline
Bring back indentation

2020-11-10 18:41 UTC, gur111 commented on lisp.tex
> +  {\unexpanded\expandafter{\fileline}} % print the content to copy.txt
indentation again

2020-11-10 18:41 UTC, gur111 commented on lisp.tex
> +  \lstinputlisting[language=kernel,style=display,backgroundcolor=\color{orange!20}]{\fileName}%
indent

2020-11-10 18:41 UTC, gur111 commented on lisp.tex
> +שפת LISP (כקיצור של \E|LIst ProceSsing|), היתה, יחד עם שפת Fortran (ראשי
Maybe `LISt Processing` but it surely isn't `LIPS`

2020-12-01 19:53 UTC, yossigil commented
I am sorry, but the dev version has converged, and there are still conflicts. Can you please create a new PR with respect to the current dev version.

2020-12-01 19:53 UTC, closed without merging