missing space & wrong tree
yossigil/safot pull request #96
Opened 2020-10-24 06:34 UTC by bitjimy

missing space in list, and tree for ((B C) C) and not ((A B) C)

2020-11-10 18:48 UTC, gur111 commented
Please merge with master to solve conflicts

2020-11-10 18:49 UTC, gur111 reviewed
Conflicts. Yes, I know, it's not your fault. But please fix conflicts and I'll CR and merge

2020-11-10 19:04 UTC, bitjimy commented
> Conflicts. Yes, I know, it's not your fault. But please fix conflicts and I'll CR and merge

done.

2020-11-14 23:36 UTC, gur111 requested changes
Let's just wait for Yossi's approval on the ones I'm not sure.
Meanwhile fix the dot thing.

2020-11-14 23:36 UTC, gur111 commented on lisp.tex
> +  \T|t| אם ארגומנט זה הוא האטום \T|nil| ואחרת את האטום \T|nil| אם הארגומנט
Add missing dot

2020-11-14 23:36 UTC, gur111 commented on lisp.tex
> +סימני הסוגריים ואת סימן הפסיק בא בהנתן אלפבית~$Σ$ אזי,~$T(Σ)$.
Not sure I agree with that fix, @yossigil ?

2020-11-14 23:36 UTC, gur111 commented on lisp.tex
> +((BAZ))
@yossigil ?

2020-11-14 23:36 UTC, gur111 commented on lisp.tex
> +((BAZ))
@yossigil ?

2020-12-01 19:55 UTC, yossigil commented
I am sorry, but the dev version has converged, and there are still conflicts. Can you please create a new PR with respect to the current dev version.

2020-12-01 19:55 UTC, closed without merging